# Generated by Django 4.1.5 on 2023-01-07 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorName', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('sensorGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensorgroup')),
            ],
        ),
    ]
